   
   <div id="sidebar-wrapper" style=" box-shadow: 3px 3px 3px rgb(193, 202, 217);">
        <ul class="sidebar-nav">
         
            </li>
            <li><a href="index.php">Edit profile</a>
            </li>
            <li><a href="?Login=AddNewTeacher">Add New Teacher</a>
            </li>
            <li><a href="#">Overview</a>
            </li>
            <li><a href="#">Events</a>
            </li>
            <li><a href="#">About</a>
            </li>
            <li><a href="#">Services</a>
            </li>
            <li><a href="#">Contact</a>
            </li>
        </ul>
    </div>
    