                         <div class="w3-card" style=" position:absolute;top:0px;left:30px;width: 1100px;height: 1000px;">
                     	   <div class="col-md-12">
                            <form  method="post" action="../Controler/NewTeacherControler.php" >
											  <div class="form-group">
											    <label >NIC</label>
											    <input type="text"  name="nic"class="form-control" required>
											  </div>
											  <div class="form-group">
											    <label >First name</label>
											    <input type="text"  name="firstname"class="form-control" required>
											  </div>
											  <div class="form-group">
											    <label >Last name</label>
											    <input type="text" name="lastname" class="form-control" required>
											  </div>
											  
											  <div class="form-group">
											    <label >Address</label>
											    <input type="text" name="address"class="form-control" required>
											  </div>

											  <div class="form-group">
											    <label >Date of birth</label>
											    <input type="date"  name="dob"class="form-control" required>
											  </div>

											  <div class="form-group">
											    <label > First appointment date</label>
											    <input type="text" name="Firstad"class="form-control" required>
											  </div>

											  <div class="form-group">
											    <label >Contact Number</label>
											    <input type="text" name="contactnumber" class="form-control" required>
											  </div>

											  <div class="form-group">
											    <label >Email</label>
											    <input type="Email" name="email" class="form-control" required>
											  </div>
											  <div class="form-group">
											    <label >Educational qualification</label>
											    <textarea class="form-control" name="eq" rows="5" id="comment"></textarea>
											  </div>
											  <div class="form-group">
											    <label >Working experience</label>
											    <textarea class="form-control" rows="5" name="we" id="comment"></textarea>
											  </div>
											  <button type="submit" name="add" class="w3-button w3-teal">ADD TEACHER</button>
                                             <!--<div class="form-group">
													<label >Picture</label>
		                                                 <input type="file" name="img" class="custom-file-input">
		                                                 <span class="custom-file-control"></span>
		                                                  <button type="submit" name="addP" class="w3-button w3-blue">UPLOAD PHOTO</button>

		                                          
		                                     </div>
		                                     registers are name, address, date of birth, contact number, first appointment date, date of present place of employment, educational qualification, working experience, extracurricular activities, attendance, leave,
-->
                                              
		     								  
									 </form> 
</div>
</div>